// <auto-generated />
using System;
using DeMol.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeMol.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240331151811_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("DeMol.Domain.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DeMol.Domain.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ContributedPrizeMoney")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContributedPrizeMoney = 0m,
                            GameId = 1,
                            IsActive = true,
                            IsMol = false,
                            IsWinner = false,
                            Name = "Bernard",
                            PhotoUrl = "https://wmimages.goplay.be/styles/f3d8f28cbac6369d15c66e328ab3944d4bcd3510/meta/bdm24nieuw-saho7d.jpg?style=W3sianBlZyI6eyJxdWFsaXR5Ijo4NX19LHsicmVzaXplIjp7ImZpdCI6ImNvdmVyIiwid2lkdGgiOjE2MCwiaGVpZ2h0IjoxNjAsImdyYXZpdHkiOm51bGwsIndpdGhvdXRFbmxhcmdlbWVudCI6ZmFsc2V9fV0=&sign=ea28199490bd4cfb4d764ba5911db6f94f52415997f17b3ed256e048c38af881"
                        },
                        new
                        {
                            Id = 2,
                            ContributedPrizeMoney = 0m,
                            GameId = 1,
                            IsActive = true,
                            IsMol = false,
                            IsWinner = false,
                            Name = "Marta(coco)",
                            PhotoUrl = "https://wmimages.goplay.be/styles/f3d8f28cbac6369d15c66e328ab3944d4bcd3510/meta/mcdm24nieuw-sahovx.jpg?style=W3sianBlZyI6eyJxdWFsaXR5Ijo4NX19LHsicmVzaXplIjp7ImZpdCI6ImNvdmVyIiwid2lkdGgiOjE2MCwiaGVpZ2h0IjoxNjAsImdyYXZpdHkiOm51bGwsIndpdGhvdXRFbmxhcmdlbWVudCI6ZmFsc2V9fV0=&sign=27a5ac56329b8ee476b7b687583a78e9893539d8685574f3e143531a93e8e0d1"
                        },
                        new
                        {
                            Id = 3,
                            ContributedPrizeMoney = 0m,
                            GameId = 1,
                            IsActive = true,
                            IsMol = false,
                            IsWinner = false,
                            Name = "Philippe",
                            PhotoUrl = "https://wmimages.goplay.be/styles/f3d8f28cbac6369d15c66e328ab3944d4bcd3510/meta/pdm24nieuw-sahp1j.jpg?style=W3sianBlZyI6eyJxdWFsaXR5Ijo4NX19LHsicmVzaXplIjp7ImZpdCI6ImNvdmVyIiwid2lkdGgiOjE2MCwiaGVpZ2h0IjoxNjAsImdyYXZpdHkiOm51bGwsIndpdGhvdXRFbmxhcmdlbWVudCI6ZmFsc2V9fV0=&sign=c02d5fab06f14ca3982627b67c48b0c3055bed691e6dbf3d1fc953746429b47b"
                        },
                        new
                        {
                            Id = 4,
                            ContributedPrizeMoney = 0m,
                            GameId = 1,
                            IsActive = true,
                            IsMol = false,
                            IsWinner = false,
                            Name = "Senne",
                            PhotoUrl = "https://wmimages.goplay.be/styles/f3d8f28cbac6369d15c66e328ab3944d4bcd3510/meta/sdm24nieuw-sahp3m.jpg?style=W3sianBlZyI6eyJxdWFsaXR5Ijo4NX19LHsicmVzaXplIjp7ImZpdCI6ImNvdmVyIiwid2lkdGgiOjE2MCwiaGVpZ2h0IjoxNjAsImdyYXZpdHkiOm51bGwsIndpdGhvdXRFbmxhcmdlbWVudCI6ZmFsc2V9fV0=&sign=ee19c47e877988a2b283fc72a0f555aaaca5ba432e55109ecb616557aadc35bb"
                        },
                        new
                        {
                            Id = 5,
                            ContributedPrizeMoney = 0m,
                            GameId = 1,
                            IsActive = true,
                            IsMol = false,
                            IsWinner = false,
                            Name = "Lynn",
                            PhotoUrl = "https://wmimages.goplay.be/styles/f3d8f28cbac6369d15c66e328ab3944d4bcd3510/meta/ldm24nieuw-sahoti.jpg?style=W3sianBlZyI6eyJxdWFsaXR5Ijo4NX19LHsicmVzaXplIjp7ImZpdCI6ImNvdmVyIiwid2lkdGgiOjE2MCwiaGVpZ2h0IjoxNjAsImdyYXZpdHkiOm51bGwsIndpdGhvdXRFbmxhcmdlbWVudCI6ZmFsc2V9fV0=&sign=5ade24f01e60fca9ca7a404fe4318eb08ebce2bff20c499f09d20d41730c60c1"
                        },
                        new
                        {
                            Id = 6,
                            ContributedPrizeMoney = 0m,
                            GameId = 1,
                            IsActive = true,
                            IsMol = false,
                            IsWinner = false,
                            Name = "Stéphanie",
                            PhotoUrl = "https://wmimages.goplay.be/styles/f3d8f28cbac6369d15c66e328ab3944d4bcd3510/meta/sbdm24nieuw-sahp5a.jpg?style=W3sianBlZyI6eyJxdWFsaXR5Ijo4NX19LHsicmVzaXplIjp7ImZpdCI6ImNvdmVyIiwid2lkdGgiOjE2MCwiaGVpZ2h0IjoxNjAsImdyYXZpdHkiOm51bGwsIndpdGhvdXRFbmxhcmdlbWVudCI6ZmFsc2V9fV0=&sign=6d07da5829f1f6620aec4ad33e4a8cb713ca95f1f13848c244c613076e548575"
                        },
                        new
                        {
                            Id = 7,
                            ContributedPrizeMoney = 0m,
                            GameId = 1,
                            IsActive = true,
                            IsMol = false,
                            IsWinner = false,
                            Name = "Charlotte",
                            PhotoUrl = "https://wmimages.goplay.be/styles/f3d8f28cbac6369d15c66e328ab3944d4bcd3510/meta/cdm24nieuw-sahomm.jpg?style=W3sianBlZyI6eyJxdWFsaXR5Ijo4NX19LHsicmVzaXplIjp7ImZpdCI6ImNvdmVyIiwid2lkdGgiOjE2MCwiaGVpZ2h0IjoxNjAsImdyYXZpdHkiOm51bGwsIndpdGhvdXRFbmxhcmdlbWVudCI6ZmFsc2V9fV0=&sign=440250844d35d1571751fc27ebae8db86274e75d5ebbc2f7aff4c59f399566a6"
                        },
                        new
                        {
                            Id = 8,
                            ContributedPrizeMoney = 0m,
                            GameId = 1,
                            IsActive = true,
                            IsMol = false,
                            IsWinner = false,
                            Name = "Michaël",
                            PhotoUrl = "https://wmimages.goplay.be/styles/f3d8f28cbac6369d15c66e328ab3944d4bcd3510/meta/mdm24nieuw-sahoy0.jpg?style=W3sianBlZyI6eyJxdWFsaXR5Ijo4NX19LHsicmVzaXplIjp7ImZpdCI6ImNvdmVyIiwid2lkdGgiOjE2MCwiaGVpZ2h0IjoxNjAsImdyYXZpdHkiOm51bGwsIndpdGhvdXRFbmxhcmdlbWVudCI6ZmFsc2V9fV0=&sign=d5961367e02cb4504d4798a44acd094671bed56bc5b14a2dfc3b968f31ab7343"
                        },
                        new
                        {
                            Id = 9,
                            ContributedPrizeMoney = 0m,
                            GameId = 1,
                            IsActive = true,
                            IsMol = false,
                            IsWinner = false,
                            Name = "Karolien",
                            PhotoUrl = "https://wmimages.goplay.be/styles/f3d8f28cbac6369d15c66e328ab3944d4bcd3510/meta/kdm24nieuw-sahora.jpg?style=W3sianBlZyI6eyJxdWFsaXR5Ijo4NX19LHsicmVzaXplIjp7ImZpdCI6ImNvdmVyIiwid2lkdGgiOjE2MCwiaGVpZ2h0IjoxNjAsImdyYXZpdHkiOm51bGwsIndpdGhvdXRFbmxhcmdlbWVudCI6ZmFsc2V9fV0=&sign=af1491127e180258c741ec809cc848e284a5a7c00e2d2d0633c3a5e03465aebb"
                        },
                        new
                        {
                            Id = 10,
                            ContributedPrizeMoney = 0m,
                            GameId = 1,
                            IsActive = false,
                            IsMol = false,
                            IsWinner = false,
                            Name = "Gillian",
                            PhotoUrl = "https://wmimages.goplay.be/styles/f3d8f28cbac6369d15c66e328ab3944d4bcd3510/meta/afvaller1roodscherm-savf4v.jpg?style=W3sianBlZyI6eyJxdWFsaXR5Ijo4NX19LHsicmVzaXplIjp7ImZpdCI6ImNvdmVyIiwid2lkdGgiOjE2MCwiaGVpZ2h0IjoxNjAsImdyYXZpdHkiOm51bGwsIndpdGhvdXRFbmxhcmdlbWVudCI6ZmFsc2V9fV0=&sign=96ec0857ab9ccbdb15371533ff4c6ee5e9444a4d595ea7a5db5e3a748c09aad2"
                        });
                });

            modelBuilder.Entity("DeMol.Domain.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrizeMoney")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrizeMoney = 0m,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("DeMol.Domain.MoleVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("VoteId");

                    b.ToTable("MoleVote");
                });

            modelBuilder.Entity("DeMol.Domain.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VotingRoundId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VotingRoundId");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("DeMol.Domain.VotingRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("VotingRounds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2024, 3, 31, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            Round = 1,
                            StartTime = new DateTime(2024, 3, 31, 17, 18, 11, 253, DateTimeKind.Local).AddTicks(2546)
                        });
                });

            modelBuilder.Entity("DeMol.Domain.WinnerVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("VoteId");

                    b.ToTable("WinnerVote");
                });

            modelBuilder.Entity("DeMol.Domain.Candidate", b =>
                {
                    b.HasOne("DeMol.Domain.Game", null)
                        .WithMany("Candidates")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeMol.Domain.MoleVote", b =>
                {
                    b.HasOne("DeMol.Domain.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeMol.Domain.Vote", null)
                        .WithMany("MoleVotes")
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("DeMol.Domain.Vote", b =>
                {
                    b.HasOne("DeMol.Domain.VotingRound", null)
                        .WithMany("Votes")
                        .HasForeignKey("VotingRoundId");
                });

            modelBuilder.Entity("DeMol.Domain.VotingRound", b =>
                {
                    b.HasOne("DeMol.Domain.Game", null)
                        .WithMany("VotingRounds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeMol.Domain.WinnerVote", b =>
                {
                    b.HasOne("DeMol.Domain.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeMol.Domain.Vote", null)
                        .WithMany("WinnerVotes")
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("DeMol.Domain.Game", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("VotingRounds");
                });

            modelBuilder.Entity("DeMol.Domain.Vote", b =>
                {
                    b.Navigation("MoleVotes");

                    b.Navigation("WinnerVotes");
                });

            modelBuilder.Entity("DeMol.Domain.VotingRound", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
